### PR TITLE
v6 readme update

### PR DESCRIPTION
**Pull request by ej2**

### CODE REVIEW

**Comment by devoto13** [comment]
Thanks for the PR, but we actually support v5 or newer, so the current text saying 5+ is correct.

**Comment by devoto13** [comment]
Also any particular reason to change the contributor section?

**Comment by ej2** [comment]
> Also any particular reason to change the contributors section?

This is prep work for the release of Font Awesome version 6 coming in Feb 2022.

**Comment by devoto13** [comment]
Hey @ej2, Thanks for the PR, but it has been hanging for a while and I still don't quite understand what problem does it aim to solve. So I'm going to close it as stale.

I've changed how do we link to the Font Awesome team in the Contributors section in https://github.com/FortAwesome/angular-fontawesome/pull/347 as it seems that should simplify the maintenance a bit. Let me know if you think that there is another issue that needs to be addressed.

**Pull request closed without merging**
