### PR TITLE
build: use ng-packagr to bundle

### PR DESCRIPTION
**Pull request by scttcper**
this uses a secondary package.json in the `/src` folder thats used only for publishing to npm

docs: https://github.com/dherges/ng-packagr
ng-packagr is what angular-cli installs for you to publish a library

### CODE REVIEW

**Comment by devoto13** [comment]
Just thinking if it makes sense to also introduce integration tests to make sure that it works with Angular 5/CLI 1.7 and Angular 6/CLI 6. And to make sure that it won't get broken in the future.

**Comment by scttcper** [comment]
i remember angular 5 broke support for angular 4 users. I'm not sure how you'd accomplish that other than having 2 sub projects that loaded the library from the build directory

**Comment by devoto13** [comment]
@scttcper that is exactly what I was thinking about.

**Comment by robmadole** [comment]
@devoto13 is this ready to merge and release? I'll do that now if you think it's ready to go but I don't have time to dive into ngPackagr and verify that this is working.

**Comment by devoto13** [comment]
@robmadole this looks good to be merged and released. It've tested it with both Angular 5 and 6 and it works. ng-packagr supports updated [Angular Packaging Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit) and seems to be much more alive than Angular Librarian.

Later on it may be better to migrate to Angular CLI (official tool) for building the library, but as @scttcper mentioned it uses ng-packagr behind the scenes, so there shouldn't be any compatibility issues and it can be done as a separate piece of work later.

The only breaking change I noticed is that UMD bundle now exports on `window.fortawesome['angular-fontawesome']` instead of `window.angularFontAwesome`. This is likely to break people, who use UMD bundles. Although I don't think that this approach is very popular, so mentioning in the changelog/upgrading instructions may be enough.

**Comment by robmadole** [comment]
OK, I need some help here. How is this package supposed to be published?

I see two `package.json` files now and we still have the `angular-librarian` stuff in there (which includes things in a `tasks` directory I think).

Can we unify these `package.json` files? Can we clean up the now unused angular-librarian stuff? Can we clean up some of the unused `scripts`? I'll document this if @scttcper or @devoto13 you can guide me here.

**Comment by scttcper** [comment]
@robmadole unfortunately going to be stuck with 2 `package.json` files for angular libraries or a bunch of code that basically hacks together a new package.json for you.

The package.json found at `src/package.json` should have the current version number, but some people change the version number in both.

to publish it should be 
```sh
npm run build
cd dist && npm publish
```

**Comment by robmadole** [comment]
Ok thanks @scttcper. That's a little...annoying...but we can live with that.

I've published 0.1.0-10. If anyone can double-check that I've done this correctly that would be appreciated.

**Comment by devoto13** [comment]
Works great 👍 
Thanks @robmadole!

This also closes https://github.com/FortAwesome/angular-fontawesome/issues/37 and obsoletes https://github.com/FortAwesome/angular-fontawesome/pull/36. No more peer dependency errors with Angular 6.

**Comment by robmadole** [comment]
Excellent! Thanks @scttcper and @devoto13 for your work on this. Super helpful and not something that would have gotten finished so fast without you both ☺️ You guys rock.

**Pull request merged**
