### PR TITLE
Feature: add prefix icon component for each icon type (fal, far, fas and fab) #108

### PR DESCRIPTION
**Pull request by ZeevKatz**

### CODE REVIEW

**Comment by zeevkatz** [comment]
@mlwilkerson So much appreciate your super fast review! And about your question...Exactly! I really think it is much more clear for using and makes the API super-convenient as @hhfrancois said in this feature request (#108).
I'll add a unit test per new prefix component and push the changes soon.

Cheers!

**Comment by devoto13** [comment]
First of all thanks for your work @zeevkatz! 

It was suggested in https://github.com/FortAwesome/angular-fontawesome/issues/10 to add `iconPrefix` and `maskPrefix` properties to set the icon prefix and at that time I didn't like the idea, based on assumption that most people will use [explicit reference](https://github.com/FortAwesome/angular-fontawesome#explicit-reference) approach over the [library](https://github.com/FortAwesome/angular-fontawesome#using-the-icon-library) approach, so this won't be a big issue. Turns out I was wrong.

In essence this implementation adds similar functionality as `iconPrefix` part of the #10, but using significantly more code. I think the same problem can be solved with much smaller change and comparable convenience by implementing the mentioned proposal instead, but naming the property `prefix` instead of `iconPrefix` (`maskPrefix` can be added later as well if necessary). E.g.

`<fa-icon prefix="far" icon="user"></fa-icon>`

vs

`<far-icon icon="user"></fa-icon>`

The property solution should also be more future proof, when more users will use custom icon packs and therefore other prefixes.

What do you think?

**Comment by devoto13** [comment]
@zeevkatz Yes, I definitely see the benefit of multiple selectors over properties at this point, but on the other hand properties not being type checked is [a regression bug](https://github.com/angular/angular/issues/24625) in Angular, which will be fixed eventually. However once these new components are out, it will be hard to take them back and we'll have to maintain them.

Also from the conceptional point of view I see `<fa-icon>` as a component to render `fontawesome-svg-core`-compatible icon. Not just amazing icons designed by FortAwesome, but custom icons as well. And from this perspective the `icon_identifier = icon_prefix + icon_name` and it feels wrong to put half of the identifier into element name instead of the components's `icon` property.

If I were to make an analogy it's like having `npm` to install any `@<namespace>/<name>` package and then introduce `npm-angular` to install only packages from `@angular/*` namespaces (e.g. `npm-angular install core` instead of `npm install @angular/core`. This does not feel right.

Another concern is that usually components in the Angular library have single prefix (`fa-` in this case), however this PR introduces 4 more prefixes to the components.

I really appreciate the effort you put into this feature and I don't want to just throw it away. But these new components do not feel right... Would be so much easier to have the discussion before the implementation.

**Comment by totkeks** [comment]
This PR hasn't seen an update in the last half year, even though the requested changes from @mlwilkerson have been completed. Any chance this could be approved or is the project abandoned?

**Comment by mlwilkerson** [comment]
@totkeks Thanks for the bump on this one. I think @devoto13 made a persuasive case that the original proposal on this PR isn't the best solution for us, so I'll go ahead and close the PR.

**Pull request closed without merging**
