### PR TITLE
Clarify community involvement

### PR DESCRIPTION
**Pull request by mlwilkerson**
The team behind Font Awesome wants to help chart a course for community-driven development of this project such that we continue to contribute but don't _block_ the community's progress in making this project awesome.

This PR aims to provide just enough structure to promote organic growth.

TODO:
- [x] Someone with adequate reputation needs to add a `angular-fontawesome` on StackOverflow
- [x] Create a template for submitting repros in an appropriate online tool (like JSFiddle)

### CODE REVIEW

**Comment by juliusstoerrle** [comment]
I would recommend to require a link to a Stackblitz App in issue template, that helped in other projects a lot with solving errors.

It might be a good idea to create a simple sample app with cli and publish it on github, People can then use this as a base to reproduce there bugs and share the stackblitz.

**Comment by mlwilkerson** [comment]
@juliusstoerrle Yes, that's the sort of thing I had in mind with that TODO item about a repro template. It's come up before, but we haven't yet nailed it down.

**Comment by MaklaCof** [comment]
StackBlitz is awesome. I would also like to recommend it.

@mlwilkerson What did you mean with 

> Someone with adequate reputation needs to add a angular-fontawesome on StackOverflow

**Comment by crhistianramirez** [comment]
@MaklaCof  I think he's referring to adding an official tag on StackOverFlow. You need a certain amount of reputation in order to create a searchable tag.

**Comment by mlwilkerson** [comment]
@MaklaCof It seems like having a StackOverflow tag specifically for `angular-fontawesome` would be fitting and helpful. But [creating a new tag requires at least 1,500 StackOverflow reputation](https://stackoverflow.com/help/privileges). I don't have that yet, but if someone else in our `angular-fontawesome` community does have 1,500 or more, then that person could possibly create a new tag for us.

**Comment by MaklaCof** [comment]
[Done](https://stackoverflow.com/questions/tagged/angular-fontawesome).

**Comment by mlwilkerson** [comment]
Thanks for creating that tag, @MaklaCof. Looks like you also tagged one or more previously created questions with that tag, [like this one](https://stackoverflow.com/questions/50189242/adding-font-awesome-5-icon-from-angular-5-component). That linked one doesn't appear to pertain to this component `@fortawesome/angular-fontawesome`. Do you intend to use the tag more broadly?

**Comment by devoto13** [comment]
I also think that StackBlitz is the best way to provide simple reproductions. I prepared a simple template [here](https://stackblitz.com/edit/angular-z8v4ux), which you can link from the issue template.

**Comment by mlwilkerson** [comment]
Thanks @devoto13. I've updated the docs with that template.

**Comment by MaklaCof** [comment]
And I added a really [short description](https://stackoverflow.com/tags/angular-fontawesome/info) for the tag.

**Comment by MaklaCof** [comment]
@mlwilkerson 
Hi. I tried to edit, but it was rejected:

> Simply defining what a [tag] is rarely helps those using it unless the tag's name itself is ambiguous. Excerpts should describe why and when a tag should be used. See the help center for more guidance.

Someone should write a more detailed description.

**Comment by mlwilkerson** [comment]
OK, thanks for setting up the tag, @MaklaCof. I just added it to a recently asked question that pertains to this component!

**Pull request merged**
