### PR TITLE
Added Travis CI

### PR DESCRIPTION
**Pull request by devoto13**
Added simple Travis CI setup to make sure that new changes don't break the library. This is very simple now, it will run `yarn lint`, `yarn build` and `yarn test` for every PR/branch to make sure nothing is broken.

As it turns out some things are broken already now 😄Just pulled the repo and was not able to `yarn build` `development` branch because of errors.

@mlwilkerson this will require some setup from you as well. Instructions are below:

1. Go to https://github.com/marketplace/travis-ci and add Travis CI extension for open source projects (it's free).
2. Go to https://travis-ci.org/, click on the tiny "+" button in the left pane and enable it for `FortAwesome/angular-fontawesome` repo.
3. Follow https://help.github.com/articles/enabling-required-status-checks guide to make `master` (and probably `development`) branch protected and enable `continuous-integration/travis-ci` status check for it.

With this we can make sure that default branch and PRs are in a good shape without running this checks manually. The failing check will be displayed in the PRs and prevent merges from everybody except repo administrators. You can see this in action in https://github.com/devoto13/angular-fontawesome/pull/1.

---

Opening this now mostly for demo and to start discussion. I think it would be better to merge 5.1 updates first and then I'll rebase this branch for merging.

### CODE REVIEW

**Comment by mlwilkerson** [comment]
Thank you, thank you, @devoto13. You read my mind about getting this set up. I'm thinking we're getting pretty close to a 1.0 release here and getting CI set up with some decent test coverage was one of those last check boxes in my mind.

**Comment by mlwilkerson** [comment]
@robmadole I'd be interested in your take on doing the protected branch thing. That would be different from how we've configured some other repos, but maybe it would be an advantageous workflow?

**Comment by robmadole** [comment]
@mlwilkerson yeah the protected branch thing is great for larger projects but I'm not sure we have that much churn on this project to warrant it. That being said I would be fine to enable it (personally I like it).

@devoto13 yeah agreed. Let's get 5.1 stuff in and this can follow soon afterwards.

**Comment by devoto13** [comment]
Protected branch is a good thing to make sure that nobody can accidentally push untested changes in it. The idea is that all changes should go through the same procedure (PR into protected branch, where all required checks - build and code review succeeded) and that master branch is always in working state.

This is generally a useful addition to [GitHub Flow](https://guides.github.com/introduction/flow/), which is simple branching model used by many projects on GitHub. I see that you guys also have separate `development` branch. Is there any reason why you decided to go with this branching model instead of GitHub Flow?

**Comment by mlwilkerson** [comment]
@devoto13 we've been using a long-running `development` branch in other repos to be the place from which we do development pre-releases. We'd then do only fast-forward merges from `development` into `master`. On second thought, though, given how small this project is, we may not need that extra layer of workflow.

**Comment by devoto13** [comment]
Closing as CI was enabled in #20.

**Pull request closed without merging**
