### PR TITLE
Added link to the StackBlitz template

### PR DESCRIPTION
**Pull request by devoto13**

### CODE REVIEW

**Comment by kbradl16** [comment]
Why not include test files?!

**Comment by devoto13** [comment]
@kbradl16 What kind of test files are you talking about?

**Comment by kbradl16** [comment]
unit test files. app.component.spec.ts

**Comment by devoto13** [comment]
@kbradl16 Well, this template is intended for quick demos and tests are not very applicable here. If you want to demonstrate bug specific to unit tests it is better to setup a complete Angular CLI project and upload it to GitHub instead.

**Pull request merged**
